### ISSUE TITLE
cannot import name 'Self' from 'typing'

### ISSUE THREAD

**Issue by TingTingShao** [aertslab/pycisTopic#125]
Hi, 

Beofore I was using the oder version of pycisTopic, and 

```python
models=run_cgs_models_mallet(
    cistopic_obj = cistopic_obj,
    n_topics=[2,5,10,15,20,25,30,35,40,45,50],
    n_cpu=55,
    n_iter=500,
    random_state=1,
    alpha=50,
    alpha_by_topic=True,
    eta=0.1,
    eta_by_topic=False,
    tmp_path= tmp_dir, 
    mallet_path = path_to_mallet_binary, # this argument is not recognized
    save_path = None)
```
So I chose to upgrade the version into `2.0a0`
Error shows like this
```
Traceback (most recent call last):
  File "./cistopic.py", line 370, in <module>
    cistopic_obj = pickle.load(open(os.path.join(work_dir, 'cistopic_obj.pkl'), 'rb'))
  File "/data/leuven/351/vsc35107/miniconda3/envs/pycistopic/lib/python3.8/site-packages/pycisTopic/cistopic_class.py", line 6, in <module>
    from typing import TYPE_CHECKING, Self
ImportError: cannot import name 'Self' from 'typing' (/data/leuven/351/vsc35107/miniconda3/envs/pycistopic/lib/python3.8/typing.py)
```

Could really use your help here.

Thanks!
tingting

**Comment by SeppeDeWinter** [comment]
Hi,

You need python 3.11 for the newest version of pycisTopic.

I pinned the python version to 3.11 https://github.com/aertslab/pycisTopic/commit/e8e5c3fb76254242e5fbf644bae8f2818cf25553.

All the best,

Seppe

**Comment by TingTingShao** [comment]
Yes, but other errors came out, will come back later if I find the solution.

But for now, the code you shared before helped!

```python
rule model_topics:
    input:
        obj_pkl="cistopic_obj1.pkl",
    output:
        topic_pkl="035results_models/models_500_iter_mallet.pkl"
    shell:
        """
        pycistopic topic_modeling mallet \
            -i {input.obj_pkl} \
            -o {output.topic_pkl} \
            -t 2 5 10 15 20 25 30 35 40 45 50 55 60 65 \
            -p 16 \
            -b {config[mallet]} \
            -T {config[tmp_dir]} \
            -k True       
        """
```

Thanks very much for your guidance!
tingting
