### ISSUE TITLE
create_cistopic_object_from_fragments: numpy.core._exceptions._ArrayMemoryError [PERFORMANCE]

### ISSUE THREAD

**Issue by DmitriiSeverinov** [aertslab/pycisTopic#130]
Hi all,

I want to create a cisTopic object and for this I'm running
```python
cistopic_obj_list = []
for sample_id in fragments_dict:
    # sample_metrics = bc_passing_filter[sample_id]
    cistopic_obj = create_cistopic_object_from_fragments(
        path_to_fragments = fragments_dict[sample_id],
        path_to_regions = path_to_regions[sample_id],
        # metrics = sample_metrics,
        # valid_bc = bc_passing_filter[sample_id],
        n_cpu = 8,
        project = sample_id,
        split_pattern = '-'
    )
    cistopic_obj_list.append(cistopic_obj)
``` 
And I'm getting the following error
```python
2024-04-11 11:28:44,392 cisTopic     INFO     Reading data for Lesion
2024-04-11 11:29:50,055 cisTopic     INFO     Counting number of unique fragments (Unique_nr_frag)
2024-04-11 11:30:16,410 cisTopic     INFO     Counting fragments in regions
2024-04-11 11:30:58,315 cisTopic     INFO     Creating fragment matrix
/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pycisTopic/cistopic_class.py:883: PerformanceWarning: The following operation may generate 268705384570 cells in the resulting pandas object.
  .unstack(level="Name", fill_value=0)
2024-04-11 11:33:35,368 cisTopic     INFO     Data is too big, making partitions. This is a reported error in Pandas versions > 0.21 (https://github.com/pandas-dev/pandas/issues/26314)
/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pycisTopic/cistopic_class.py:951: PerformanceWarning: The following operation may generate 52883251047 cells in the resulting pandas object.
  .unstack(level="Name", fill_value=0)
Traceback (most recent call last):
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pycisTopic/cistopic_class.py", line 883, in create_cistopic_object_from_fragments
    .unstack(level="Name", fill_value=0)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pandas/core/series.py", line 4458, in unstack
    return unstack(self, level, fill_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pandas/core/reshape/reshape.py", line 493, in unstack
    return unstacker.get_result(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pandas/core/reshape/reshape.py", line 216, in get_result
    values, _ = self.get_new_values(values, fill_value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pandas/core/reshape/reshape.py", line 268, in get_new_values
    new_values = np.empty(result_shape, dtype=dtype)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 1.96 TiB for an array with shape (561485, 478562) and data type int64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pycisTopic/cistopic_class.py", line 908, in create_cistopic_object_from_fragments
    cistopic_obj_list = [
                        ^
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pycisTopic/cistopic_class.py", line 909, in <listcomp>
    create_cistopic_object_chunk(
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pycisTopic/cistopic_class.py", line 951, in create_cistopic_object_chunk
    .unstack(level="Name", fill_value=0)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pandas/core/series.py", line 4458, in unstack
    return unstack(self, level, fill_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pandas/core/reshape/reshape.py", line 493, in unstack
    return unstacker.get_result(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pandas/core/reshape/reshape.py", line 216, in get_result
    values, _ = self.get_new_values(values, fill_value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/biotec_poetsch/dmse952c/miniconda3/envs/new_scenicplus/lib/python3.11/site-packages/pandas/core/reshape/reshape.py", line 268, in get_new_values
    new_values = np.empty(result_shape, dtype=dtype)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 394. GiB for an array with shape (552519, 95713) and data type int64
``` 
Obviously, there is a memory issue here. My dataset has only 14k cells in total. They are distributed across 2 conditions: condition 1 ~6.5k, condition 2 ~7.5k

It was working fine on this dataset before. The only thing I've changed is the cell type annotation. Before it was a crude one with only 14 cell types. Now, I want to go a little bit more in details, therefore I made it more fine-grained, resulting in 28 cell types. 

I work now on a cluster with 500Gb RAM. Apparently, this is not enough. I have an option switching to the server with more RAM available, but my concern is that soon I will get more data and I can't increase RAM indefinitely.

**Version information**

pycisTopic: '2.0a0'

Best,
Dmitrii

**Comment by ghuls** [comment]
There is some work in progress that would replace the current code with a smarter version that will use quite a bit less RAM.

**Comment by ghuls** [comment]
`(561485, 478562)` and `(552519, 95713)` still look way to big if you only have 14k cells.

**Comment by DmitriiSeverinov** [comment]
Hi @ghuls ,

I am sorry, I think I found the issue for my case, I had the `valid_bc` parameter being commented...

Sorry for bothering.

Best,
Dmitrii

**Comment by LJK1991** [comment]
Hello @ghuls,

I have the same error as @DmitriiSeverinov. I however, do not have the `valid_bc` commented out.

When running this chunk:
```
cistopic_obj_list = []
for sample_id in fragments_dic:
    sample_metrics = pl.read_parquet(os.path.join(pycistopic_qc_output_dir, f'{sample_id}.fragments_stats_per_cb.parquet')).to_pandas().set_index("CB").loc[ sample_id_to_barcodes_passing_filters[sample_id] ]
    print(sample_metrics.shape)
    cistopic_obj = create_cistopic_object_from_fragments(
        path_to_fragments = fragments_dic[sample_id],
        path_to_regions = path_to_regions,
        path_to_blacklist = path_to_blacklist,
        metrics = sample_metrics,
        valid_bc = sample_id_to_barcodes_passing_filters[sample_id],
        n_cpu = 2,
        project = sample_id,
        split_pattern = '-',#does this need to be changed?
        partition=8 #will hopefully take care of memory erros, it does not.
    )
    cistopic_obj_list.append(cistopic_obj)
```
```
2025-05-16 08:35:18,165 cisTopic     INFO     Reading data for E7.5_rep1
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/l.kuijpers/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/cistopic_class.py", line 816, in create_cistopic_object_from_fragments
    fragments = read_fragments_to_pyranges(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/l.kuijpers/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/fragments.py", line 164, in read_fragments_to_pyranges
    return pr.PyRanges(df)
           ^^^^^^^^^^^^^^^
  File "/home/l.kuijpers/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pyranges/pyranges.py", line 177, in __init__
    _init(self, df, chromosomes, starts, ends, strands, int64, copy_df)
  File "/home/l.kuijpers/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pyranges/methods/init.py", line 155, in _init
    df = df.reset_index(drop=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/l.kuijpers/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/l.kuijpers/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pandas/core/frame.py", line 6298, in reset_index
    new_obj = self.copy(deep=None)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/l.kuijpers/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pandas/core/generic.py", line 6373, in copy
    data = self._mgr.copy(deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/l.kuijpers/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 645, in copy
    res = self.apply("copy", deep=deep)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/l.kuijpers/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 348, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/l.kuijpers/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pandas/core/internals/blocks.py", line 550, in copy
    values = values.copy()
             ^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.04 GiB for an array with shape (1, 273572070) and data type int64
```
I am using pycisTopic on the (Argelaguet mouse dataset)[https://www.biorxiv.org/content/10.1101/2022.06.15.496239v2] and want to continue with pyscenicplus.

There are quite a bit of cells in the dataset and after QC these are the amounts.
**NOTE** i did change some of the threshold values to better fit the plots.
here is a screenshot of the first sample.

![Image](https://github.com/user-attachments/assets/4e141996-a880-41b6-ab76-883ba2d213a2)

I first ran it with automated thresholding which did work, but had a lot less cells and few overlaped with the RNA part of the dataset. hence I am trying to relax the thresholds a bit.
```
[len(sample_id_to_barcodes_passing_filters[key]) for key in sample_id_to_barcodes_passing_filters.keys()]
[8366, 12411, 3557, 6213, 5329, 10296, 9958, 3730, 5127]
```
However, i'd like to believe that RAM usage should not be an issue as i'm working on a server with ~400GB of RAM.
I'm not sure what is going wrong. Especially because in this example it stops at the first sample 'E7.5_rep1' but a previous run I was able to get to the third sample. 

@ghuls maybe you have some suggestions or im just making some basic errors.
If neccesary i can send files.

**Comment by ruohuchengxhe** [comment]
Hi @LJK1991 , @DmitriiSeverinov 
 I'm having the same issue, I used `valid_bc=None` because I was using data from signac so i skipped QC, I have ~7k cells, but after this function, I have ~225k cells. I tried to provide barcodes to valid_bc, but got the same result.
