### ISSUE TITLE
models

### ISSUE THREAD

**Issue by TingTingShao** [aertslab/pycisTopic#140]
Hi, 

The job:
```bash
shell:
    """
    pycistopic topic_modeling mallet \
        -i {input.obj_pkl} \
        -o {output.topic_pkl} \
        -t 2 5 10 20 30 35 40 45 50 55 60 65 70 80 90\
        -p 16 \
        -b {config[mallet]} \
        -T {config[tmp_dir]} \
        -k True       
    """
```
After submitting the job to the server, I realized that the each model will take 4-5 hours to complete, but I set up 36hours for this job.

I know this job will fail eventually, could I please ask if there is a way, for example

The job stopped after finishing model with 45 topics, is it possible for me to run again with only `50 55 60 65 70 80 90`, 

```bash
    pycistopic topic_modeling mallet \
        -i {input.obj_pkl} \
        -o {output.topic_pkl} \
        -t 50 55 60 65 70 80 90\
        -p 16 \
        -b {config[mallet]} \
        -T {config[tmp_dir]} \
        -k True 
```
Assume the last run is successful, and it generates one .pkl file? how to add the models from previous run to the .pkl file? I tried with an example with append, but didn't look very right.

Thanks!
tingting

**Comment by TingTingShao** [comment]
Another question is that I have another job to run the Snakefile for topic modelling, but the job disrupted the previous job for topic modeling, is there a better way to manage the workflow?

I isolated the topic modelling step in one single Snakefile, and then each work-dir has a corresponding config file.

error
```
2024-05-09 22:40:21,320 cisTopic     INFO     Running model with 50 topics
2024-05-09 22:40:21,352 LDAMalletWrapper INFO     Serializing temporary corpus to /scratch/leuven/351/vsc35107/corpus.txt
2024-05-09 22:49:33,405 LDAMalletWrapper INFO     Converting temporary corpus to MALLET format with: /vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/Mallet/bin/mallet import-file --preserve-case --keep-sequence --token-regex \S+ --input /scratch/leuven/351/vsc35107/corpus.txt --output /scratch/leuven/351/vsc35107/corpus.mallet
2024-05-09 23:03:29,450 LDAMalletWrapper INFO     Training MALLET LDA with: /vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/Mallet/bin/mallet train-topics --input /scratch/leuven/351/vsc35107/corpus.mallet --num-topics 50 --alpha 50 --beta 0.1 --optimize-interval 0 --num-threads 16 --output-state /scratch/leuven/351/vsc35107/8e041_state.mallet.gz --output-doc-topics /scratch/leuven/351/vsc35107/8e041_doctopics.txt --outpu2024-05-11 05:38:47,344 LDAMalletWrapper INFO     loading assigned topics from /scratch/leuven/351/vsc35107/2bc360_state.mallet.gz
Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/bin/pycistopic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/pycisTopic/cli/pycistopic.py", line 26, in main
    args.func(args)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/pycisTopic/cli/subcommand/topic_modeling.py", line 123, in run_topic_modeling_mallet
    models = run_cgs_models_mallet(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/pycisTopic/lda_models.py", line 809, in run_cgs_models_mallet
    model_list = [
                 ^
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/pycisTopic/lda_models.py", line 810, in <listcomp>
    run_cgs_model_mallet(
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/pycisTopic/lda_models.py", line 942, in run_cgs_model_mallet
    arun_2010 = tmtoolkit.topicmod.evaluate.metric_arun_2010(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/tmtoolkit/topicmod/evaluate.py", line 174, in metric_arun_2010
    cm2 = doc_lengths @ doc_topic_distrib
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 160310 is different from 270072)
[Sat May 11 05:41:12 2024]
--- Logging error ---
Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/executors/local.py", line 420, in run_wrapper
    run(
  File "/vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/snap2_pipeline/Snakefile02", line 61, in __rule_model_topics
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/shell.py", line 297, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        pycistopic topic_modeling mallet             -i /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/cistopic_obj.pkl             -o /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/020models/models_500_iter_mallet.pkl             -t 2 5 10 20 30 40 45 50 55 60 70 80 90             -p 16             -b /vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/Mallet/bin/mallet             -T /scratch/leuven/351/vsc35107/             -k True' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/executors/local.py", line 259, in _callback
    raise ex
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/executors/local.py", line 245, in cached_or_run
    run_func(*args)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/executors/local.py", line 456, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/snap2_pipeline/Snakefile02, line 31:
Command 'set -euo pipefail;  
        pycistopic topic_modeling mallet             -i /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/cistopic_obj.pkl             -o /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/020models/models_500_iter_mallet.pkl             -t 2 5 10 20 30 40 45 50 55 60 70 80 90             -p 16             -b /vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/Mallet/bin/mallet             -T /scratch/leuven/351/vsc35107/             -k True' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1114, in emit
    self.flush()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1094, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Call stack:
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/concurrent/futures/thread.py", line 60, in run
    self.future.set_exception(exc)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/concurrent/futures/_base.py", line 565, in set_exception
    self._invoke_callbacks()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/executors/local.py", line 272, in _callback
    self.report_job_error(job_info)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/base.py", line 92, in report_job_error
    self.print_job_error(job_info, msg, **kwargs)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/base.py", line 113, in print_job_error
    job_info.job.log_error(msg, **kwargs)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/jobs.py", line 997, in log_error
    logger.job_error(**self.get_log_error_info(msg, indent, aux_logs, **kwargs))
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 418, in job_error
    self.handler(msg)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 359, in handler
    handler(msg)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 588, in text_handler
    timestamp()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 529, in timestamp
    self.logger.info(indent(f"[{time.asctime()}]"))
Message: '[Sat May 11 05:41:12 2024]'
Arguments: ()
Error in rule model_topics:
    jobid: 1
    input: /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/cistopic_obj.pkl
    output: /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/020models/models_500_iter_mallet.pkl
    shell:
        
        pycistopic topic_modeling mallet             -i /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/cistopic_obj.pkl             -o /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/020models/models_500_iter_mallet.pkl             -t 2 5 10 20 30 40 45 50 55 60 70 80 90             -p 16             -b /vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/Mallet/bin/mallet             -T /scratch/leuven/351/vsc35107/             -k True       
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

--- Logging error ---
Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/executors/local.py", line 420, in run_wrapper
    run(
  File "/vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/snap2_pipeline/Snakefile02", line 61, in __rule_model_topics
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/shell.py", line 297, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        pycistopic topic_modeling mallet             -i /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/cistopic_obj.pkl             -o /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/020models/models_500_iter_mallet.pkl             -t 2 5 10 20 30 40 45 50 55 60 70 80 90             -p 16             -b /vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/Mallet/bin/mallet             -T /scratch/leuven/351/vsc35107/             -k True' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/executors/local.py", line 259, in _callback
    raise ex
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/executors/local.py", line 245, in cached_or_run
    run_func(*args)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/executors/local.py", line 456, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/snap2_pipeline/Snakefile02, line 31:
Command 'set -euo pipefail;  
        pycistopic topic_modeling mallet             -i /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/cistopic_obj.pkl             -o /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/020models/models_500_iter_mallet.pkl             -t 2 5 10 20 30 40 45 50 55 60 70 80 90             -p 16             -b /vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/Mallet/bin/mallet             -T /scratch/leuven/351/vsc35107/             -k True' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1114, in emit
    self.flush()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1094, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Call stack:
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/concurrent/futures/thread.py", line 60, in run
    self.future.set_exception(exc)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/concurrent/futures/_base.py", line 565, in set_exception
    self._invoke_callbacks()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/executors/local.py", line 272, in _callback
    self.report_job_error(job_info)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/base.py", line 92, in report_job_error
    self.print_job_error(job_info, msg, **kwargs)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/base.py", line 113, in print_job_error
    job_info.job.log_error(msg, **kwargs)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/jobs.py", line 997, in log_error
    logger.job_error(**self.get_log_error_info(msg, indent, aux_logs, **kwargs))
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 418, in job_error
    self.handler(msg)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 359, in handler
    handler(msg)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 589, in text_handler
    self.logger.error("\n".join(map(indent, job_error())))
Message: 'Error in rule model_topics:\n    jobid: 1\n    input: /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/cistopic_obj.pkl\n    output: /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/020models/models_500_iter_mallet.pkl\n    shell:\n        \n        pycistopic topic_modeling mallet             -i /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/cistopic_obj.pkl             -o /lustre1/project/stg_00079/students/tingting/data/sun/snap2_PFC_synapse/01/030results_cistopic/020models/models_500_iter_mallet.pkl             -t 2 5 10 20 30 40 45 50 55 60 70 80 90             -p 16             -b /vsc-hard-mounts/leuven-data/351/vsc35107/master_thesis/Mallet/bin/mallet             -T /scratch/leuven/351/vsc35107/             -k True       \n        \n        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)\n'
Arguments: ()
Shutting down, this might take some time.
--- Logging error ---
Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1114, in emit
    self.flush()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1094, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Call stack:
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/bin/snakemake", line 8, in <module>
    sys.exit(main())
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/cli.py", line 2091, in main
    success = args_to_api(args, parser)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/cli.py", line 2014, in args_to_api
    dag_api.execute_workflow(
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/api.py", line 590, in execute_workflow
    workflow.execute(
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/workflow.py", line 1235, in execute
    success = self.scheduler.schedule()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/scheduler.py", line 217, in schedule
    logger.info("Shutting down, this might take some time.")
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 386, in info
    self.handler(dict(level="info", msg=msg, indent=indent))
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 359, in handler
    handler(msg)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 617, in text_handler
    self.logger.warning(msg["msg"])
Message: 'Shutting down, this might take some time.'
Arguments: ()
Exiting because a job execution failed. Look above for error message
--- Logging error ---
Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1114, in emit
    self.flush()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1094, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Call stack:
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/bin/snakemake", line 8, in <module>
    sys.exit(main())
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/cli.py", line 2091, in main
    success = args_to_api(args, parser)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/cli.py", line 2014, in args_to_api
    dag_api.execute_workflow(
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/api.py", line 590, in execute_workflow
    workflow.execute(
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/workflow.py", line 1235, in execute
    success = self.scheduler.schedule()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/scheduler.py", line 220, in schedule
    logger.error(_ERROR_MSG_FINAL)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 397, in error
    self.handler(dict(level="error", msg=msg))
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 359, in handler
    handler(msg)
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 621, in text_handler
    self.logger.error(msg["msg"])
Message: 'Exiting because a job execution failed. Look above for error message'
Arguments: ()
Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/cli.py", line 2014, in args_to_api
    dag_api.execute_workflow(
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/api.py", line 590, in execute_workflow
    workflow.execute(
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/workflow.py", line 1275, in execute
    self._onerror(logger.get_logfile())
                  ^^^^^^^^^^^^^^^^^^^^
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 353, in get_logfile
    self.logfile_handler.flush()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1094, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1192, in close
    self.flush()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1094, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle

During handling of the above exception, another exception occurred:

OSError: [Errno 116] Stale file handle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/cli.py", line 2091, in main
    success = args_to_api(args, parser)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/cli.py", line 1842, in args_to_api
    with SnakemakeApi(
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/api.py", line 287, in __exit__
    self._cleanup()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/api.py", line 163, in _cleanup
    logger.cleanup()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/site-packages/snakemake/logging.py", line 348, in cleanup
    self.logfile_handler.close()
  File "/data/leuven/351/vsc35107/miniconda3/envs/scenic2/lib/python3.11/logging/__init__.py", line 1197, in close
    stream.close()
OSError: [Errno 116] Stale file handle
```

**Comment by TingTingShao** [comment]
Thread https://github.com/aertslab/pycisTopic/issues/106 solved my first question.

**Comment by yojetsharma** [comment]
Hi, any idea how i can import modules like pycistopic.diff_features while running it as a job? pycistopic module gets imported when i submit the job on SGE but not the specific modules like diff_features, normalize_scores. These are normally imported in jupyter or python though.
