### ISSUE TITLE
Calling export_pseudobulk returns TypeError in function enable_string_cache()  [BUG]

### ISSUE THREAD

**Issue by ashleighthomas** [aertslab/pycisTopic#151]
**Describe the bug**
export_pseudobulk as written in tutorial for pycisTopic at https://pycistopic.readthedocs.io/en/latest/notebooks/human_cerebellum.html results in error. This happens when I run this on my own dataset in addition to the tutorial dataset. It sounds like this sort of error is often when no arguments are listed in a python function but self is actually passed in.

**To Reproduce**
Run the tutorial at the above link but on own data (scRNA and scATAC). The error is specifically in export_pseudobulk. The code I am running is identical to the tutorial, just on different data.

**Error output**
Stack trace:
```2024-07-23 12:55:10,175 cisTopic     INFO     Splitting fragments by cell type.
2024-07-23 12:58:24,889 cisTopic     INFO     generating bigwig files
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/BCCRC.CA/athomas/Documents/scenicPlusWork/pycisTopic/src/pycisTopic/pseudobulk_peak_calling.py", line 32, in _generate_bigwig
    fragments_df = read_fragments_to_polars_df(path_to_fragments)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/scatac_fragment_tools/library/bigwig/fragments_to_bigwig.py", line 223, in read_fragments_to_polars_df
    fragments_df_pl = read_bed_to_polars_df(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/scatac_fragment_tools/library/bigwig/fragments_to_bigwig.py", line 127, in read_bed_to_polars_df
    pl.enable_string_cache(True)
TypeError: enable_string_cache() takes 0 positional arguments but 1 was given
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/run/user/1287634658/gvfs/smb-share:server=crcfile11.bccrc.ca,share=hoodlesslab/AshleighThomas/hccTumourProj/scenicPlusWork/tutorialPycisTopic.py", line 154, in <module>
    bw_paths, bed_paths = export_pseudobulk(
                          ^^^^^^^^^^^^^^^^^^
  File "/home/BCCRC.CA/athomas/Documents/scenicPlusWork/pycisTopic/src/pycisTopic/pseudobulk_peak_calling.py", line 184, in export_pseudobulk
    joblib.Parallel(n_jobs=n_cpu)(
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
TypeError: enable_string_cache() takes 0 positional arguments but 1 was given
```

**Expected behavior**
I expect pseudobulk bed and bw files to be generated, as per the tutorial.

**Screenshots**
If applicable, add screenshots to help explain your problem or show the format of the input data for the command/s.

**Version (please complete the following information):**
 - Python: python 3.11.9
 - pycisTopic: 2.0a0

Please let me know if this should actually be filed under scenicPlus, as I am trying to run this tutorial in the process of the overall scenicPlus tutorial on my own data. Thank you!

**Comment by gilgolan73** [comment]
Hello,
I have the same problem. Can you please elaborate on the solution?

Thank you,
Gil

**Comment by ashleighthomas** [comment]
Unfortunately I changed several things at once and am not sure which fixed
the problem. However for me I believe starting from scratch with a fresh
conda env was helpful.

**Comment by gilgolan73** [comment]
Hi,
I am using a new conda env and it is still not working.
Which version of polars / polars-lts-cpu are you using?

Gil

**Comment by ashleighthomas** [comment]
[requirements.txt](https://github.com/user-attachments/files/16447550/requirements.txt)
I've attached my requirements file here. polars is 0.20.13. I will not be able to answer further questions.
