### ISSUE TITLE
pycistopic qc error

### ISSUE THREAD

**Issue by Yiming-Huang-neuron** [aertslab/pycisTopic#163]
Dear, author. Can you help me how to solve the problems with the pycistopic qc error?
I'm getting the following error for run pycistopic qc.
I try to test one sample of my data. This is my code.
<img width="1106" alt="qc_code" src="https://github.com/user-attachments/assets/03cf3183-c285-4314-8825-b19ae0797263">

However, an error occurred in the log file, as follows:
<img width="1132" alt="code_log" src="https://github.com/user-attachments/assets/686d0bd3-099e-4552-ae81-1b0b6bb9af0b">

I do not know how to fix, please help me.

All the best

Yiming

**Comment by ghuls** [comment]
You can apply this patch (from the `polars_1xx` branch):
https://github.com/aertslab/pycisTopic/commit/7d9a9ccd19a87925ffee0d33139411e77d462e5a

Or you can change your fragment file to not have the same count value for each fragment (changing one of the counts should be enough).

**Comment by Yiming-Huang-neuron** [comment]
Thank you very much for your response. The issue has been successfully resolved.

**Comment by danli349** [comment]
@ghuls Hi @ghuls 
I have the same issue, I used the 'qc.py' from (polars_1xx branch) and my fragments file does not have the same count value for each fragment 

<img width="546" height="306" alt="Image" src="https://github.com/user-attachments/assets/0b0dc17f-f125-48da-ad60-67c1d713f6cf" />
But this error still exist:

```
cat pycistopic_qc_commands.txt | parallel -j 6 {}
/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/__init__.py:3: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
Traceback (most recent call last):
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 226, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 574, in set_bandwidth
    self._compute_covariance()
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 586, in _compute_covariance
    self._data_cho_cov = linalg.cholesky(self._data_covariance,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/linalg/_decomp_cholesky.py", line 88, in cholesky
    c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/linalg/_decomp_cholesky.py", line 36, in _cholesky
    raise LinAlgError("%d-th leading minor of the array is not positive "
numpy.linalg.LinAlgError: 1-th leading minor of the array is not positive definite

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dan/miniconda3/envs/scenicplus/bin/pycistopic", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/cli/pycistopic.py", line 26, in main
    args.func(args)
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/cli/subcommand/qc.py", line 233, in run_qc
    qc(
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/cli/subcommand/qc.py", line 144, in qc
    ) = compute_qc_stats(
        ^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/qc.py", line 605, in compute_qc_stats
    pdf_values_for_tss_enrichment = compute_kde(
                                    ^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/qc.py", line 217, in compute_kde
    for pdf_result in executor.map(compute_kde_part, test_data_unique_split_arrays):
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/qc.py", line 210, in compute_kde_part
    return gaussian_kde(training_data)(test_data_unique_split_array)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 235, in __init__
    raise linalg.LinAlgError(msg) from e
numpy.linalg.LinAlgError: The data appears to lie in a lower-dimensional subspace of the space in which it is expressed. This has resulted in a singular data covariance matrix, which cannot be treated using the algorithms implemented in `gaussian_kde`. Consider performing principle component analysis / dimensionality reduction and using `gaussian_kde` with the transformed data.
/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/__init__.py:3: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
Traceback (most recent call last):
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 226, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 574, in set_bandwidth
    self._compute_covariance()
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 586, in _compute_covariance
    self._data_cho_cov = linalg.cholesky(self._data_covariance,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/linalg/_decomp_cholesky.py", line 88, in cholesky
    c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/linalg/_decomp_cholesky.py", line 36, in _cholesky
    raise LinAlgError("%d-th leading minor of the array is not positive "
numpy.linalg.LinAlgError: 1-th leading minor of the array is not positive definite

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dan/miniconda3/envs/scenicplus/bin/pycistopic", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/cli/pycistopic.py", line 26, in main
    args.func(args)
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/cli/subcommand/qc.py", line 233, in run_qc
    qc(
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/cli/subcommand/qc.py", line 144, in qc
    ) = compute_qc_stats(
        ^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/qc.py", line 605, in compute_qc_stats
    pdf_values_for_tss_enrichment = compute_kde(
                                    ^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/qc.py", line 217, in compute_kde
    for pdf_result in executor.map(compute_kde_part, test_data_unique_split_arrays):
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/qc.py", line 210, in compute_kde_part
    return gaussian_kde(training_data)(test_data_unique_split_array)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 235, in __init__
    raise linalg.LinAlgError(msg) from e
numpy.linalg.LinAlgError: The data appears to lie in a lower-dimensional subspace of the space in which it is expressed. This has resulted in a singular data covariance matrix, which cannot be treated using the algorithms implemented in `gaussian_kde`. Consider performing principle component analysis / dimensionality reduction and using `gaussian_kde` with the transformed data.
/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/__init__.py:3: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
Traceback (most recent call last):
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 226, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 574, in set_bandwidth
    self._compute_covariance()
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 586, in _compute_covariance
    self._data_cho_cov = linalg.cholesky(self._data_covariance,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/linalg/_decomp_cholesky.py", line 88, in cholesky
    c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/linalg/_decomp_cholesky.py", line 36, in _cholesky
    raise LinAlgError("%d-th leading minor of the array is not positive "
numpy.linalg.LinAlgError: 1-th leading minor of the array is not positive definite

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dan/miniconda3/envs/scenicplus/bin/pycistopic", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/cli/pycistopic.py", line 26, in main
    args.func(args)
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/cli/subcommand/qc.py", line 233, in run_qc
    qc(
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/cli/subcommand/qc.py", line 144, in qc
    ) = compute_qc_stats(
        ^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/qc.py", line 605, in compute_qc_stats
    pdf_values_for_tss_enrichment = compute_kde(
                                    ^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/qc.py", line 217, in compute_kde
    for pdf_result in executor.map(compute_kde_part, test_data_unique_split_arrays):
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/pycisTopic/qc.py", line 210, in compute_kde_part
    return gaussian_kde(training_data)(test_data_unique_split_array)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/scenicplus/lib/python3.11/site-packages/scipy/stats/_kde.py", line 235, in __init__
    raise linalg.LinAlgError(msg) from e
numpy.linalg.LinAlgError: The data appears to lie in a lower-dimensional subspace of the space in which it is expressed. This has resulted in a singular data covariance matrix, which cannot be treated using the algorithms implemented in `gaussian_kde`. Consider performing principle component analysis / dimensionality reduction and using `gaussian_kde` with the transformed data.
```

Could you please let me know how to solve it ? Thanks a lot

**Comment by danli349** [comment]
@ghuls sorry I solved this problem, the reason is beause the chromosome names is 1 2 3... which I have to change to chr1 chr2 chr3... to consistent with the tss.bed file. Thanks
