### ISSUE TITLE
export_pseudobulk never generates pseudobulk bed and bw files as output

### ISSUE THREAD

**Issue by mervedede** [aertslab/pycisTopic#41]
Hello,

Thank you very much for developing this nice tool for the community. I am trying to run the scenicplus pipeline and having issues in the export_pseudobulk step. I am using the fragment files for my scATAC-seq samples and have generated a cell_data matrix that has a "barcode" as well as "sample_id" columns that match the keys of the fragments dictionary.

When I run the following :
````
from pycisTopic.pseudobulk_peak_calling import export_pseudobulk

bw_paths, bed_paths = export_pseudobulk(input_data = cell_data,
                 variable = 'celltype',                                                                     # variable by which to generate pseubulk profiles, in this case we want pseudobulks per celltype
                 sample_id_col = 'sample_id',
                 chromsizes = chromsizes,
                 bed_path = os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bed_files/'),  # specify where pseudobulk_bed_files should be stored
                 bigwig_path = os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bw_files/'),# specify where pseudobulk_bw_files should be stored
                 path_to_fragments = fragments_dict,                                                        # location of fragment fiels
                 n_cpu = 8,                                                                                 # specify the number of cores to use, we use ray for multi processing
                 normalize_bigwig = True,
                 remove_duplicates = True,
                 _temp_dir = os.path.join(tmp_dir, 'ray_spill'),
                 split_pattern = '-') # 
````

I get a prompt that the fragment files are being read, then the pseudobulks start being created but I never get the "done!" message and when I check the folder that should have the bed and bw files, I see that the files are not generated. The only errors I keep getting are the following including errors related to frame.append and division by zero for some samples:

````
2022-09-19 16:08:32,721 cisTopic     INFO     Reading fragments from /Users/md/Fragment_files/SC122_1.tsv.gz

2022-09-19 16:09:56,641 cisTopic     INFO     Reading fragments from /Users/md/Fragment_files/SC122_2.tsv.gz

2022-09-19 16:11:07,895 cisTopic     INFO     Reading fragments from /Users/md/Fragment_files/SC122_3.tsv.gz

2022-09-19 16:12:29,169 cisTopic     INFO     Reading fragments from /Users/md/Fragment_files/SC122_4.tsv.gz

2022-09-19 16:14:20,169 cisTopic     INFO     Reading fragments from
/Users/md/Fragment_files/SC122_5.tsv.gz

2022-09-19 16:22:01,379	INFO worker.py:1509 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 

(export_pseudobulk_ray pid=34502) 2022-09-19 16:22:06,040 cisTopic     INFO     Creating pseudobulk for IL12_GBM_3
(export_pseudobulk_ray pid=34502) /Users/md/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/pseudobulk_peak_calling.py:273: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
(export_pseudobulk_ray pid=34502)   group_fragments = group_fragments_list[0].append(group_fragments_list[1:])

(export_pseudobulk_ray pid=34506) 2022-09-19 16:22:07,105 cisTopic     INFO     Creating pseudobulk for IL12_GBM_9
(export_pseudobulk_ray pid=34506) /Users/md/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/pseudobulk_peak_calling.py:273: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
(export_pseudobulk_ray pid=34506)   group_fragments = group_fragments_list[0].append(group_fragments_list[1:])

(export_pseudobulk_ray pid=34502) 2022-09-19 16:22:08,506 cisTopic     INFO     Creating pseudobulk for IL15_GBM_3

(export_pseudobulk_ray pid=34502) 2022-09-19 16:22:10,977 cisTopic     INFO     Creating pseudobulk for IL15_baseline
(export_pseudobulk_ray pid=34502) /Users/md/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/pseudobulk_peak_calling.py:273: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
(export_pseudobulk_ray pid=34502)   group_fragments = group_fragments_list[0].append(group_fragments_list[1:])
2022-09-19 16:22:13,123	ERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::export_pseudobulk_ray() (pid=34502, ip=127.0.0.1)
  File "/Users/md/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/pseudobulk_peak_calling.py", line 345, in export_pseudobulk_ray
    export_pseudobulk_one_sample(
  File "/Users/md/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/pseudobulk_peak_calling.py", line 284, in export_pseudobulk_one_sample
    group_pr.to_bigwig(
  File "/Users/md/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pyranges/pyranges.py", line 5339, in to_bigwig
    result = _to_bigwig(self, path, chromosome_sizes, rpm, divide, value_col, dryrun)
  File "/Users/md/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pyranges/out.py", line 164, in _to_bigwig
    gr = self.to_rle(rpm=rpm, strand=False, value_col=value_col).to_ranges()
  File "/Users/md/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pyranges/pyranges.py", line 5634, in to_rle
    return _to_rle(self, value_col, strand=strand, rpm=rpm, nb_cpu=nb_cpu)
  File "/Users/md/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pyranges/methods/to_rle.py", line 25, in _to_rle
    multiplier = 1e6 / len(ranges)
ZeroDivisionError: float division by zero

(export_pseudobulk_ray pid=34506) 2022-09-19 16:22:14,672 cisTopic     INFO     Creating pseudobulk for IL21_baseline
(export_pseudobulk_ray pid=34506) /Users/md/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/pseudobulk_peak_calling.py:273: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
(export_pseudobulk_ray pid=34506)   group_fragments = group_fragments_list[0].append(group_fragments_list[1:])
````

I appreciate any kind of advice on this issue.

Thanks

**Comment by cbravo93** [comment]
Hi @mervedede !

This error indicates that the pseudobulks are empty. This will happen if there is no overlap between the barcodes in your barcode column and your fragments files, likely because you are not formatting the barcodes correctly in the cell_data. Can you check if this is the case? Can you show us a view of your cell_data and one of your fragments files?

Cheers!

C

**Comment by mervedede** [comment]
Oh, that solves my problem! Apparently, it was a formatting error from "-"s vs "_"s . Thank you so much!

**Comment by massonix** [comment]
Hi,

I am facing a similar problem. In particular, the code runs correctly, but I don't get any output written in the paths that are returned by the function, nor I get the "done!" message. This is the code that I run:

```
bw_paths, bed_paths = export_pseudobulk(
    input_data = cell_data, 
    variable = "annotation_20230727", # variable by which to generate pseubulk profiles, in this case we want pseudobulks per cell state
    sample_id_col = "gem_id",
    chromsizes = chromsizes,
    bed_path = path_to_bed,
    bigwig_path = path_to_bw,
    path_to_fragments = path_to_fragments_12,
    n_cpu = 12,
    normalize_bigwig = True,
    remove_duplicates = True,
    _temp_dir = path_tmp,
    split_pattern = "_"
)
```

This is what the cell_data dataframe looks like:

![image](https://github.com/aertslab/pycisTopic/assets/35916509/defea40d-5aa5-463a-8a2d-f0cc60e9f6ab)

As you can see, I have two samples, which I name following the conventions [in this paper](https://academic.oup.com/gigascience/article/6/11/gix100/4557140?login=false). I have a barcode column with the cell barcode, which contains the gem_id (sample id) as a prefix. Importantly, the fragments file contains the cell barcodes in the same format. Example:

![image](https://github.com/aertslab/pycisTopic/assets/35916509/825a9235-edf1-4514-88ac-830b3a21aa74)
 
The path_to_fragments_12 is a dictionary with two paths, with keys set to the two "gem_ids", which are specified in the sample_id_col parameter.

Could it be related with the fact that the "gem_id" already has one "_" contained in the id itself?

Thanks for your help!

**Comment by SeppeDeWinter** [comment]
Hi @massonix 

This will most likely be the issue indeed. Could you try removing the underscore from the "gem_id"?

Best,

Seppe

**Comment by massonix** [comment]
Hi Seppe,

I could work around it by specifying the "barcode" variable in cell_data, and everything worked fine!

Now I'm struggling with a similar issue to create a cystopic object from fragments files and consensus peaks. That's the code I'm running:

```
sample = "mysample"
obj = create_cistopic_object_from_fragments(
    path_to_fragments = path_fragments_dict[sample],
    path_to_regions = path_to_regions[sample],
    path_to_blacklist = path_to_blacklist,
    metrics = metrics_bc[sample],
    valid_bc = list(set(scRNA_bc) & set(scATAC_bc)),
    n_cpu = 12,
    project = sample,
   split_pattern = None
)
```

That's the error:

```
2023-09-01 11:58:39,310 cisTopic     INFO     Reading data for auujgiou_y7yo6t8f
2023-09-01 12:00:30,045 cisTopic     INFO     metrics provided!
2023-09-01 12:00:37,181 cisTopic     INFO     valid_bc provided, selecting barcodes!
2023-09-01 12:00:43,674 cisTopic     INFO     Counting fragments in regions
2023-09-01 12:01:32,253 cisTopic     INFO     Creating fragment matrix
/home/groups/singlecell/rmassoni/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/cistopic_class.py:881: PerformanceWarning: The following operation may generate 2882762080 cells in the resulting pandas object.
  counts_df.groupby(["Name", "regionID"], sort=False, observed=True)
2023-09-01 12:02:38,063 cisTopic     INFO     Converting fragment matrix to sparse matrix
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/groups/singlecell/rmassoni/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/cistopic_class.py", line 888, in create_cistopic_object_from_fragments
    cistopic_obj = create_cistopic_object(
  File "/home/groups/singlecell/rmassoni/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/cistopic_class.py", line 568, in create_cistopic_object
    cell_names = [
  File "/home/groups/singlecell/rmassoni/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/cistopic_class.py", line 569, in <listcomp>
    cell_names[x] + split_pattern + project for x in range(len(cell_names))
TypeError: can only concatenate str (not "NoneType") to str
```

I looked at the code for this function, and the error comes from this chunk inside the create_cistopic_object function :

```
if tag_cells:
     cell_names = [
     cell_names[x] + split_pattern + project for x in range(len(cell_names))
     ]
```

tag_cells is the key parameter: if I can set it to False, then pycistopic will take the cell barcodes that are within my fragments file and barcodes list and not try to append anything to it. I could set this tag conveniently if I could run the create_cistopic_object function directly. However, I depend on the create_cistopic_object_from_fragments function which doesn't include the tag_cells parameter, and therefore it's set to True by default.

Could you please explain me how I could get a work-around? I have a lot of other data that depend on the cell barcodes being named this way, so I could really appreciate if I could run this without going to the beginning. Also, I think users should have the option of including the tag or not in this function

Thank you!

**Comment by SeppeDeWinter** [comment]
Hi @mervedede 

The easiest is to set the `split_pattern` to a string (not `None`). I would suggest to use something different from `"_"` because that character is already used in your barcodes. That way still a tag will be added to each barcode. The "split_pattern" will be used to separate the barcode from the sample name (`"mysample"` in your case). In case of a single sample this is not really necessary, but once you start analysing data from multiple samples this becomes important (to avoid barcode collisions across samples).

That being said, you are correct that the user should be able to decide wether he/she wants to add the tag or not. 
I'll update the code accordingly soon.

Best,

Seppe
