### ISSUE TITLE
`create_cistopic_object_from_fragments`: no attribute: "regionID"  [BUG]

### ISSUE THREAD

**Issue by alexlenail** [aertslab/pycisTopic#60]
Following the multi-sample multiome tutorial with my data, I run into this error when trying to create cistopic objects. 

```
2023-01-30 15:15:58,302 cisTopic     INFO     Reading data for 102
2023-01-30 15:25:57,681 cisTopic     INFO     metrics provided!
2023-01-30 15:26:20,581 cisTopic     INFO     valid_bc provided, selecting barcodes!
2023-01-30 15:26:22,462 cisTopic     INFO     Counting fragments in regions
join: Strand data from other will be added as strand data to self.
If this is undesired use the flag apply_strand_suffix=False.
To turn off the warning set apply_strand_suffix to True or False.

Traceback (most recent call last):
  File "/var/spool/slurmd/job21276321/slurm_script", line 274, in impute
    cistopic_obj = create_cistopic_object_from_fragments(
  File "/home/gridsan/lenail/.conda/envs/py39/lib/python3.9/site-packages/pycisTopic/cistopic_class.py", line 870, in create_cistopic_object_from_fragments
    fragments_in_regions.regionID.astype("category"),
  File "/home/gridsan/lenail/.conda/envs/py39/lib/python3.9/site-packages/pyranges/pyranges.py", line 269, in __getattr__
    return _getattr(self, name)
  File "/home/gridsan/lenail/.conda/envs/py39/lib/python3.9/site-packages/pyranges/methods/attr.py", line 67, in _getattr
    raise AttributeError("PyRanges object has no attribute", name)
AttributeError: ('PyRanges object has no attribute', 'regionID')
```

Presumably this line is causing the problem: https://github.com/aertslab/pycisTopic/blob/242c2a47aad475250f8abb2469a0e36085d6e460/pycisTopic/cistopic_class.py#L866

**Comment by cbravo93** [comment]
Hi @alexlenail !

Can you post the head of the pseudobulk consensus peaks and the number of regions and the head of the fragments file?  

Cheers!

C

**Comment by alexlenail** [comment]
`consensus_regions.bed`: 

```
(base) lenail@login-2:~$ head -n 40 neuroTF_shared/mouse_brain_aging/ATAC/pseudobulks/motor/consensus_regions.bed
GL456221.1	85840	86340	L4_5ITCTX_old_peak_1,L2_3ITCTX_old_peak_1,L6CTCTX_old_peak_1,L5ITCTX_old_peak_1	0.9247113860175316	.
GL456239.1	22507	23007	Endo_young_peak_1	1.5070442144746496	.
GL456239.1	24538	25038	L4_5ITCTX_old_peak_2b	0.633120523825132	.
GL456239.1	25147	25647	L4_5ITCTX_old_peak_3	0.32677188326458423	.
GL456239.1	34345	34845	Micro_PVM_young_peak_1	0.7584548234313723	.
GL456239.1	35939	36439	Micro_PVM_young_peak_2,Astro_young_peak_1	0.5975704669459297	.
GL456239.1	23906	24406	L4_5ITCTX_old_peak_2a,L5ITCTX_old_peak_2	1.4908967173946657	.
GL456239.1	38454	38954	Astro_young_peak_2,Micro_PVM_old_peak_1,Micro_PVM_young_peak_3,L4_5ITCTX_old_peak_4,VLMC_young_peak_1,L4_5ITCTX_young_peak_1a,L4_5ITCTX_young_peak_1b,L4_5ITCTX_young_peak_1c,L4_5ITCTX_young_peak_1d,Astro_young_peak_3	3.071370983222636	.
JH584295.1	1261	1761	L6ITCTX_young_peak_1b,L6ITCTX_young_peak_1c,SMC_Peri_young_peak_2,Sncg_young_peak_1,SMC_Peri_old_peak_1,L6CTCTX_young_peak_1e,L5PTCTX_old_peak_1c,L5PTCTX_old_peak_1d,L5PTCTX_old_peak_1e,VLMC_old_peak_2,Endo_young_peak_2b,Endo_young_peak_2c,L4_5ITCTX_old_peak_5c,L2_3ITCTX_young_peak_1c,L2_3ITCTX_young_peak_1d,L5_6NPCTX_old_peak_2a,L5_6NPCTX_old_peak_2b,L5ITCTX_old_peak_3c,L5ITCTX_old_peak_3d,L5ITCTX_old_peak_3e,L2_3ITENTl_old_peak_2,L5ITCTX_young_peak_1e,L4RSP_ACA_old_peak_1,L5PTCTX_young_peak_1d,Sst_young_peak_1d,Sst_young_peak_1e,Lamp5_old_peak_1a,L2_3ITCTX_old_peak_2c,L2_3ITCTX_old_peak_2d,Astro_young_peak_4c,L2_3ITPPP_young_peak_2,Vip_old_peak_1b,Oligo_young_peak_1d,Oligo_young_peak_1e,Lamp5_young_peak_2a,Micro_PVM_young_peak_4d,L4_5ITCTX_young_peak_2c,Endo_old_peak_1b,Vip_young_peak_1b,DG_old_peak_1,L6ITCTX_old_peak_2,L6ITCTX_young_peak_1d,Micro_PVM_old_peak_2c,Micro_PVM_old_peak_2d,Micro_PVM_old_peak_2e,L6CTCTX_old_peak_2c,VLMC_young_peak_3,L2_3ITPPP_old_peak_2a,L2_3ITPPP_old_peak_2b,L5_6NPCTX_young_peak_1c,Astro_old_peak_2a,Astro_old_peak_2b,Sst_old_peak_1c,Sst_old_peak_1d,Pvalb_young_peak_1b,Pvalb_young_peak_1c	451.7440547255655	.
JH584295.1	260	760	L5ITCTX_young_peak_1a,L5ITCTX_young_peak_1b,L6CTCTX_young_peak_1a,L6CTCTX_young_peak_1b,L6CTCTX_young_peak_1c,Pvalb_old_peak_1a,Pvalb_old_peak_1b,L6ITCTX_young_peak_1a,L6ITCTX_young_peak_1b,Astro_young_peak_4a,SMC_Peri_young_peak_1,L5PTCTX_old_peak_1a,L5PTCTX_old_peak_1b,VLMC_old_peak_1,L2_3ITPPP_old_peak_1,Micro_PVM_old_peak_2a,Micro_PVM_old_peak_2b,Endo_old_peak_1a,Vip_young_peak_1a,L5PTCTX_young_peak_1a,L5PTCTX_young_peak_1b,L5PTCTX_young_peak_1c,L2_3ITENTl_old_peak_1,L6ITCTX_old_peak_1a,L6ITCTX_old_peak_1b,L2_3ITCTX_old_peak_2a,L2_3ITCTX_old_peak_2b,Oligo_old_peak_1a,Oligo_old_peak_1b,L4_5ITCTX_young_peak_2a,L4_5ITCTX_young_peak_2b,Endo_young_peak_2a,L5ITCTX_old_peak_3a,L5ITCTX_old_peak_3b,Sst_young_peak_1b,Sst_young_peak_1c,L4_5ITCTX_old_peak_5a,L4_5ITCTX_old_peak_5b,Oligo_young_peak_1a,Oligo_young_peak_1b,Oligo_young_peak_1c,L5_6NPCTX_old_peak_1a,L5_6NPCTX_old_peak_1b,L2_3ITCTX_young_peak_1a,L2_3ITCTX_young_peak_1b,L6CTCTX_old_peak_2a,L6CTCTX_old_peak_2b,Sst_old_peak_1a,Sst_old_peak_1b,Pvalb_young_peak_1a,Astro_old_peak_1a,Astro_old_peak_1b,L5_6NPCTX_young_peak_1a,L5_6NPCTX_young_peak_1b,Vip_old_peak_1a,Lamp5_young_peak_1,L5ITCTX_young_peak_1b,L5ITCTX_young_peak_1c,L5ITCTX_young_peak_1d,L6CTCTX_young_peak_1b,L6CTCTX_young_peak_1c,L6CTCTX_young_peak_1d,Astro_young_peak_4b,Micro_PVM_young_peak_4b,Micro_PVM_young_peak_4c,Pvalb_old_peak_1b,Pvalb_old_peak_1c,L2_3ITPPP_young_peak_1	26.418934556072077	.
JH584304.1	7866	8366	Micro_PVM_young_peak_9,Micro_PVM_young_peak_10a	0.7584548234313723	.
JH584304.1	15036	15536	Micro_PVM_old_peak_10g,Micro_PVM_young_peak_13	2.179248768274976	.
JH584304.1	17660	18160	Micro_PVM_young_peak_16,VLMC_old_peak_6	2.297809580191831	.
```

`print(regions)` added to cistopic_class.py:
```
+--------------+-----------+-----------+------------------------+
| Chromosome   | Start     | End       | regionID               |
| (category)   | (int32)   | (int32)   | (object)               |
|--------------+-----------+-----------+------------------------|
| GL456221.1   | 85840     | 86340     | GL456221.1:85840-86340 |
| GL456239.1   | 22507     | 23007     | GL456239.1:22507-23007 |
| GL456239.1   | 24538     | 25038     | GL456239.1:24538-25038 |
| GL456239.1   | 25147     | 25647     | GL456239.1:25147-25647 |
| ...          | ...       | ...       | ...                    |
| GL456221.1   | 85840     | 86340     | GL456221.1:85840-86340 |
| chrY         | 90748585  | 90749085  | chrY:90748585-90749085 |
| chrY         | 90808252  | 90808752  | chrY:90808252-90808752 |
| chrY         | 90815306  | 90815806  | chrY:90815306-90815806 |
| chrY         | 90823150  | 90823650  | chrY:90823150-90823650 |
+--------------+-----------+-----------+------------------------+
Unstranded PyRanges object has 875,382 rows and 4 columns from 25 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
```

`zcat atac_fragments.tsv.gz | head -n 100`
```
# id=tube102_batch2_young1_cageA_motor
# description=tube102_batch2_young1_cageA_motor
#
# pipeline_name=cellranger-arc
# pipeline_version=cellranger-arc-2.0.2
#
# reference_path=/data1/groups/neuroTF/cellranger_references/mm39/GRCm39
# reference_fasta_hash=91e360c3ac0ff645e71e93d8354cbdd6c77b1000
# reference_gtf_hash=aa9c13bbe7938e1515676ea4ea825872a553e8fe
# reference_version=
# mkref_version=cellranger-arc-2.0.2
#
# primary_contig=chr1
# primary_contig=chr2
# primary_contig=chr3
# primary_contig=chr4
# primary_contig=chr5
# primary_contig=chr6
# primary_contig=chr7
# primary_contig=chr8
# primary_contig=chr9
# primary_contig=chr10
# primary_contig=chr11
# primary_contig=chr12
# primary_contig=chr13
# primary_contig=chr14
# primary_contig=chr15
# primary_contig=chr16
# primary_contig=chr17
# primary_contig=chr18
# primary_contig=chr19
# primary_contig=chrX
# primary_contig=chrY
# primary_contig=GL456210.1
# primary_contig=GL456211.1
# primary_contig=GL456212.1
# primary_contig=GL456219.1
# primary_contig=GL456221.1
# primary_contig=GL456239.1
# primary_contig=GL456354.1
# primary_contig=GL456372.1
# primary_contig=GL456381.1
# primary_contig=GL456385.1
# primary_contig=JH584295.1
# primary_contig=JH584296.1
# primary_contig=JH584297.1
# primary_contig=JH584298.1
# primary_contig=JH584299.1
# primary_contig=JH584303.1
# primary_contig=JH584304.1
chr1	3049977	3050136	CGCTGTGCACCTGTAA-1	1
chr1	3049998	3050053	GTTGCATAGTTATTCC-1	1
chr1	3050029	3050177	ACACAATGTCTCAGCC-1	1
chr1	3050034	3050423	CCTACTGGTTGAGGTC-1	1
chr1	3050046	3050250	GCAGGCAAGTAAACCC-1	6
chr1	3050046	3050260	GCCTCGACAATTAGCT-1	2
chr1	3050046	3050611	TACGTAATCGTGCTTC-1	1
chr1	3050051	3050242	TTAAGTGTCCGGTATG-1	2
chr1	3050061	3050165	CGCTATGAGCATGGTT-1	1
chr1	3050075	3050242	GTCCAAGTCAGGAACA-1	1
chr1	3050111	3050152	TTAAGCCAGTGAAGTG-1	4
chr1	3050118	3050460	ACATTAGTCCGGTTAG-1	1
chr1	3050126	3051138	ACCGGTTCAAGCGAGC-1	1
```

**Comment by alexlenail** [comment]
Important update: it looks like the join is resulting in an `Empty PyRanges`

**Comment by alexlenail** [comment]
I think this was as simple as a mismatch in the format of my barcodes provided via `metrics` and the barcodes in the fragments file.

**Comment by alexlenail** [comment]
Could be nice to check for this / leave a warning message.

**Comment by fidelle** [comment]
Hi , please was this issue resolved? I am having the same error. I recently downloaded scenicplus.

**Comment by TingTingShao** [comment]
Have you fixed it? I have the same error.

```bash
(snap2) bash-4.4$ head consensus_regions.bed 
chr1    818005  818505  4_peak_4        1.647283983235806       .
chr1    819488  819988  5_peak_4        0.8524466070067701      .
chr1    924763  925263  5_peak_11       1.3260280553438646      .
chr1    939998  940498  2_peak_11       0.41805683886026196     .
chr1    940678  941178  5_peak_12       1.8469676485146687      .
chr1    941375  941875  2_peak_12       0.6147894689121499      .
chr1    955370  955870  1_peak_8        1.0452890911241217      .
chr1    975996  976496  1_peak_11       1.0452890911241217      .
chr1    1015339 1015839 3_peak_15       2.3050788895051944      .
chr1    1021047 1021547 6_peak_12       2.9734938510271087      .
```

```bash
(snap2) bash-4.4$ zcat 000fragments/D19-12513.fragments.Mic.tsv.gz | head
chr1    180776  180813  TGATCAGAGATCGAGC-1      1
chr1    187056  187130  GCCTAGGAGCTAGCAG-1      3
chr1    191510  191721  GTACTTTGTAATGCAA-1      1
chr1    634005  634058  TGATCAGAGATCGAGC-1      5
chr1    777846  778064  TACTCGCTCTTCCAGC-1      1
chr1    778414  778617  GCACGGTTCCAAGTCA-1      1
chr1    778419  778662  CCTGGGACAAACTACC-1      1
chr1    778602  778844  TTTACGTAGTGCACAG-1      1
chr1    778603  778844  TTTACGTAGTGCACAG-1      1
chr1    778610  778853  GCACGGTTCCAAGTCA-1      1
```

**Comment by TingTingShao** [comment]
> I think this was as simple as a mismatch in the format of my barcodes provided via `metrics` and the barcodes in the fragments file.

Mine looks like they are the same format.

```bash
print(metadata_bc['D19-12696'])
                    Log_total_nr_frag  Log_unique_nr_frag  Total_nr_frag  Unique_nr_frag  Dupl_nr_frag  Dupl_rate  Total_nr_frag_in_regions  Unique_nr_frag_in_regions      FRIP  TSS_enrichment
AGCTATGTCCCTACGT-1           4.014772            3.933690          10346            8584          1762   0.170307                      7400                       6105  0.711207        6.294521
ACAGACTGTCTCAAAC-1           4.352067            4.284949          22494           19273          3221   0.143194                     10264                       8702  0.451512        5.556924
TTACTTGGTGGTGGTA-1           4.338297            4.264346          21792           18380          3412   0.156571                     10126                       8445  0.459467        4.076131
CTCAGCTTCGACTTAG-1           3.684037            3.619198           4831            4161           670   0.138688                      2408                       2043  0.490988        5.845545
GACCCAGAGTCCTTCC-1           3.699664            3.632052           5008            4286           722   0.144169                      1919                       1618  0.377508        5.341577
...                               ...                 ...            ...             ...           ...        ...                       ...                        ...       ...             ...
AACAGTCAGCACCATT-1           3.462548            3.373647           2901            2364           537   0.185109                       824                        666  0.281726        7.746023
TCAGGTAAGGGAGTTC-1           3.261025            3.180699           1824            1516           308   0.168860                       763                        610  0.402375        5.258595
ACAGAAATCCATGTTT-1           3.153205            3.073352           1423            1184           239   0.167955                       204                        155  0.130912        2.335000
ACTGCAACATATTGGC-1           3.158362            3.094471           1440            1243           197   0.136806                       743                        640  0.514883        5.482022
CTACTTAGTCAGACGA-1           3.395326            3.341830           2485            2197           288   0.115895                       931                        811  0.369140        5.661077
```

```python
(snap2) bash-4.4$ zcat 000fragments/D19-12513.fragments.Mic.tsv.gz | head
chr1    180776  180813  TGATCAGAGATCGAGC-1      1
chr1    187056  187130  GCCTAGGAGCTAGCAG-1      3
chr1    191510  191721  GTACTTTGTAATGCAA-1      1
chr1    634005  634058  TGATCAGAGATCGAGC-1      5
chr1    777846  778064  TACTCGCTCTTCCAGC-1      1
chr1    778414  778617  GCACGGTTCCAAGTCA-1      1
chr1    778419  778662  CCTGGGACAAACTACC-1      1
chr1    778602  778844  TTTACGTAGTGCACAG-1      1
chr1    778603  778844  TTTACGTAGTGCACAG-1      1
chr1    778610  778853  GCACGGTTCCAAGTCA-1      1
```

**Comment by TingTingShao** [comment]
Problem solved.

In my case, I need to exclude the samples with zero cell left.

```python
excluded_keys = []
for samID in unique_samples:
    if len(bc_passing_filters[samID]) == 0:
        excluded_keys.append(samID)

cistopic_obj_list=[create_cistopic_object_from_fragments(path_to_fragments=fragments_dict[key],
                                               path_to_regions=path_to_regions[key],
                                               path_to_blacklist=path_to_blacklist,
                                               metrics=metadata_bc[key],
                                               valid_bc=bc_passing_filters[key],
                                               n_cpu=1,
                                               project=key) for key in fragments_dict.keys() if key not in excluded_keys]
```
