### ISSUE TITLE
Large data run problems in 'run_cgs_models_mallet' Bug report [BUG]

### ISSUE THREAD

**Issue by WangRong423** [aertslab/pycisTopic#67]
**Describe the bug**
I report the following error when running 'run_cgs_models_mallet' with 40 sample composition objects(CistopicObject from project cisTopic_merge with n_cells × n_regions = 412962 × 514566). 

**To Reproduce**
from pycisTopic.lda_models import *
import os
os.environ['MALLET_MEMORY'] = '250G'

outDir = '/database/wangrong/Results/0712_ATAC+RNA/SCENIC/models/'
path_to_mallet_binary='/home/zhang_lab/software/mallet-2.0.8/bin/mallet'
models=run_cgs_models_mallet(path_to_mallet_binary,
                    cistopic_obj,
                    n_topics=[10,16],
                    n_cpu=48,
                    n_iter=500,
                    random_state=555,
                    alpha=50,
                    alpha_by_topic=True,
                    eta=0.1,
                    eta_by_topic=False,
                    tmp_path='/DATA1/wangrong/temp/ray_spill/', #Use SCRATCH if many models or big data set
                    save_path='/DATA1/wangrong/temp/ray_spill/')
# Save
with open('/database/wangrong/Results/0712_ATAC+RNA/SCENIC/models/muliti_model_16.pkl', 'wb') as f:
  pickle.dump(models, f)

**Error output**
2023-02-09 22:51:59,156 cisTopic     INFO     Formatting input to corpus
2023-02-09 22:53:55,234 gensim.corpora.dictionary INFO     adding document #0 to Dictionary<0 unique tokens: []>
2023-02-09 22:54:34,468 gensim.corpora.dictionary INFO     adding document #10000 to Dictionary<0 unique tokens: []>
2023-02-09 22:55:22,226 gensim.corpora.dictionary INFO     adding document #20000 to Dictionary<0 unique tokens: []>
2023-02-09 22:56:09,277 gensim.corpora.dictionary INFO     adding document #30000 to Dictionary<0 unique tokens: []>
2023-02-09 22:57:01,954 gensim.corpora.dictionary INFO     adding document #40000 to Dictionary<0 unique tokens: []>
2023-02-09 22:57:47,592 gensim.corpora.dictionary INFO     adding document #50000 to Dictionary<0 unique tokens: []>
2023-02-09 22:58:28,260 gensim.corpora.dictionary INFO     adding document #60000 to Dictionary<0 unique tokens: []>
2023-02-09 22:59:08,554 gensim.corpora.dictionary INFO     adding document #70000 to Dictionary<0 unique tokens: []>
2023-02-09 22:59:50,094 gensim.corpora.dictionary INFO     adding document #80000 to Dictionary<0 unique tokens: []>
2023-02-09 23:00:48,477 gensim.corpora.dictionary INFO     adding document #90000 to Dictionary<0 unique tokens: []>
2023-02-09 23:01:58,252 gensim.corpora.dictionary INFO     adding document #100000 to Dictionary<0 unique tokens: []>
2023-02-09 23:03:04,565 gensim.corpora.dictionary INFO     adding document #110000 to Dictionary<0 unique tokens: []>
2023-02-09 23:03:49,255 gensim.corpora.dictionary INFO     adding document #120000 to Dictionary<0 unique tokens: []>
2023-02-09 23:04:53,093 gensim.corpora.dictionary INFO     adding document #130000 to Dictionary<0 unique tokens: []>
2023-02-09 23:06:09,246 gensim.corpora.dictionary INFO     adding document #140000 to Dictionary<0 unique tokens: []>
2023-02-09 23:06:55,646 gensim.corpora.dictionary INFO     adding document #150000 to Dictionary<0 unique tokens: []>
2023-02-09 23:08:00,640 gensim.corpora.dictionary INFO     adding document #160000 to Dictionary<0 unique tokens: []>
2023-02-09 23:09:08,255 gensim.corpora.dictionary INFO     adding document #170000 to Dictionary<0 unique tokens: []>
2023-02-09 23:10:24,462 gensim.corpora.dictionary INFO     adding document #180000 to Dictionary<0 unique tokens: []>
2023-02-09 23:11:45,149 gensim.corpora.dictionary INFO     adding document #190000 to Dictionary<0 unique tokens: []>
2023-02-09 23:13:14,400 gensim.corpora.dictionary INFO     adding document #200000 to Dictionary<0 unique tokens: []>
2023-02-09 23:14:09,895 gensim.corpora.dictionary INFO     adding document #210000 to Dictionary<0 unique tokens: []>
2023-02-09 23:15:10,515 gensim.corpora.dictionary INFO     adding document #220000 to Dictionary<0 unique tokens: []>
2023-02-09 23:16:09,592 gensim.corpora.dictionary INFO     adding document #230000 to Dictionary<0 unique tokens: []>
2023-02-09 23:17:10,590 gensim.corpora.dictionary INFO     adding document #240000 to Dictionary<0 unique tokens: []>
2023-02-09 23:18:31,039 gensim.corpora.dictionary INFO     adding document #250000 to Dictionary<0 unique tokens: []>
2023-02-09 23:19:52,745 gensim.corpora.dictionary INFO     adding document #260000 to Dictionary<0 unique tokens: []>
2023-02-09 23:21:26,767 gensim.corpora.dictionary INFO     adding document #270000 to Dictionary<0 unique tokens: []>
2023-02-09 23:23:05,618 gensim.corpora.dictionary INFO     adding document #280000 to Dictionary<0 unique tokens: []>
2023-02-09 23:24:35,329 gensim.corpora.dictionary INFO     adding document #290000 to Dictionary<0 unique tokens: []>
2023-02-09 23:25:42,783 gensim.corpora.dictionary INFO     adding document #300000 to Dictionary<0 unique tokens: []>
2023-02-09 23:26:39,197 gensim.corpora.dictionary INFO     adding document #310000 to Dictionary<0 unique tokens: []>
2023-02-09 23:28:05,725 gensim.corpora.dictionary INFO     adding document #320000 to Dictionary<0 unique tokens: []>
2023-02-09 23:29:37,389 gensim.corpora.dictionary INFO     adding document #330000 to Dictionary<0 unique tokens: []>
2023-02-09 23:30:47,121 gensim.corpora.dictionary INFO     adding document #340000 to Dictionary<0 unique tokens: []>
2023-02-09 23:32:12,502 gensim.corpora.dictionary INFO     adding document #350000 to Dictionary<0 unique tokens: []>
2023-02-09 23:33:53,167 gensim.corpora.dictionary INFO     adding document #360000 to Dictionary<0 unique tokens: []>
2023-02-09 23:35:24,437 gensim.corpora.dictionary INFO     adding document #370000 to Dictionary<0 unique tokens: []>
2023-02-09 23:36:51,900 gensim.corpora.dictionary INFO     adding document #380000 to Dictionary<0 unique tokens: []>
2023-02-09 23:38:12,206 gensim.corpora.dictionary INFO     adding document #390000 to Dictionary<0 unique tokens: []>
2023-02-09 23:39:25,703 gensim.corpora.dictionary INFO     adding document #400000 to Dictionary<0 unique tokens: []>
2023-02-09 23:40:27,890 gensim.corpora.dictionary INFO     adding document #410000 to Dictionary<0 unique tokens: []>
2023-02-09 23:40:38,671 gensim.corpora.dictionary INFO     built Dictionary<514566 unique tokens: ['0', '1', '2', '3', '4']...> from 412962 documents (total 3279924257 corpus positions)
2023-02-09 23:40:38,673 cisTopic     INFO     Running model with 10 topics
2023-02-09 23:40:38,684 LDAMalletWrapper INFO     Serializing temporary corpus to /DATA1/wangrong/temp/ray_spill/corpus.txt
2023-02-10 00:37:08,000 LDAMalletWrapper INFO     Converting temporary corpus to MALLET format with /home/zhang_lab/software/mallet-2.0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input /DATA1/wangrong/temp/ray_spill/corpus.txt --output /DATA1/wangrong/temp/ray_spill/corpus.mallet

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at cc.mallet.pipe.CharSequence2TokenSequence.pipe(CharSequence2TokenSequence.java:68)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:295)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:291)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:291)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.types.InstanceList.addThruPipe(InstanceList.java:267)
	at cc.mallet.classify.tui.Csv2Vectors.main(Csv2Vectors.java:290)

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Input In [4], in <cell line: 7>()
      5 outDir = '/database/wangrong/Results/0712_ATAC+RNA/SCENIC/models/'
      6 path_to_mallet_binary='/home/zhang_lab/software/mallet-2.0.8/bin/mallet'
----> 7 models=run_cgs_models_mallet(path_to_mallet_binary,
      8                     cistopic_obj,
      9                     n_topics=[10,16],
     10                     n_cpu=48,
     11                     n_iter=500,
     12                     random_state=555,
     13                     alpha=50,
     14                     alpha_by_topic=True,
     15                     eta=0.1,
     16                     eta_by_topic=False,
     17                     tmp_path='/DATA1/wangrong/temp/ray_spill/', #Use SCRATCH if many models or big data set
     18                     save_path='/DATA1/wangrong/temp/ray_spill/')
     19 # Save
     20 with open('/database/wangrong/Results/0712_ATAC+RNA/SCENIC/models/muliti_model_16.pkl', 'wb') as f:

File /usr/local/lib/python3.8/dist-packages/pycisTopic/lda_models.py:765, in run_cgs_models_mallet(path_to_mallet_binary, cistopic_obj, n_topics, n_cpu, n_iter, random_state, alpha, alpha_by_topic, eta, eta_by_topic, top_topics_coh, tmp_path, save_path, reuse_corpus)
    762 names_dict = {x: str(x) for x in range(len(region_names))}
    763 id2word = corpora.Dictionary.from_corpus(corpus, names_dict)
--> 765 model_list = [
    766     run_cgs_model_mallet(
    767         path_to_mallet_binary,
    768         binary_matrix,
    769         corpus,
    770         id2word,
    771         n_topics=n_topic,
    772         cell_names=cell_names,
    773         region_names=region_names,
    774         n_cpu=n_cpu,
    775         n_iter=n_iter,
    776         random_state=random_state,
    777         alpha=alpha,
    778         alpha_by_topic=alpha_by_topic,
    779         eta=eta,
    780         eta_by_topic=eta_by_topic,
    781         top_topics_coh=top_topics_coh,
    782         tmp_path=tmp_path,
    783         save_path=save_path,
    784         reuse_corpus=reuse_corpus,
    785     )
    786     for n_topic in n_topics
    787 ]
    788 return model_list

File /usr/local/lib/python3.8/dist-packages/pycisTopic/lda_models.py:766, in <listcomp>(.0)
    762 names_dict = {x: str(x) for x in range(len(region_names))}
    763 id2word = corpora.Dictionary.from_corpus(corpus, names_dict)
    765 model_list = [
--> 766     run_cgs_model_mallet(
    767         path_to_mallet_binary,
    768         binary_matrix,
    769         corpus,
    770         id2word,
    771         n_topics=n_topic,
    772         cell_names=cell_names,
    773         region_names=region_names,
    774         n_cpu=n_cpu,
    775         n_iter=n_iter,
    776         random_state=random_state,
    777         alpha=alpha,
    778         alpha_by_topic=alpha_by_topic,
    779         eta=eta,
    780         eta_by_topic=eta_by_topic,
    781         top_topics_coh=top_topics_coh,
    782         tmp_path=tmp_path,
    783         save_path=save_path,
    784         reuse_corpus=reuse_corpus,
    785     )
    786     for n_topic in n_topics
    787 ]
    788 return model_list

File /usr/local/lib/python3.8/dist-packages/pycisTopic/lda_models.py:873, in run_cgs_model_mallet(path_to_mallet_binary, binary_matrix, corpus, id2word, n_topics, cell_names, region_names, n_cpu, n_iter, random_state, alpha, alpha_by_topic, eta, eta_by_topic, top_topics_coh, tmp_path, save_path, reuse_corpus)
    871 start = time.time()
    872 log.info(f"Running model with {n_topics} topics")
--> 873 model = LDAMallet(
    874     path_to_mallet_binary,
    875     corpus=corpus,
    876     id2word=id2word,
    877     num_topics=n_topics,
    878     iterations=n_iter,
    879     alpha=alpha,
    880     eta=eta,
    881     n_cpu=n_cpu,
    882     tmp_dir=tmp_path,
    883     random_seed=random_state,
    884     reuse_corpus=reuse_corpus,
    885 )
    886 end_time = time.time() - start
    888 # Get distributions

File /usr/local/lib/python3.8/dist-packages/pycisTopic/lda_models.py:471, in LDAMallet.__init__(self, mallet_path, num_topics, corpus, alpha, eta, id2word, n_cpu, tmp_dir, optimize_interval, iterations, topic_threshold, random_seed, reuse_corpus)
    469 self.random_seed = random_seed
    470 if corpus is not None:
--> 471     self.train(corpus, reuse_corpus)

File /usr/local/lib/python3.8/dist-packages/pycisTopic/lda_models.py:537, in LDAMallet.train(self, corpus, reuse_corpus)
    535 logger = logging.getLogger("LDAMalletWrapper")
    536 if os.path.isfile(self.fcorpusmallet()) is False or reuse_corpus is False:
--> 537     self.convert_input(corpus, infer=False)
    538 else:
    539     logger.info("MALLET corpus already exists, training model")

File /usr/local/lib/python3.8/dist-packages/pycisTopic/lda_models.py:522, in LDAMallet.convert_input(self, corpus, infer, serialize_corpus)
    520     cmd = cmd % (self.fcorpustxt(), self.fcorpusmallet())
    521 logger.info("Converting temporary corpus to MALLET format with %s", cmd)
--> 522 check_output(args=cmd, shell=True)

File /usr/local/lib/python3.8/dist-packages/gensim/utils.py:1894, in check_output(stdout, *popenargs, **kwargs)
   1892         error = subprocess.CalledProcessError(retcode, cmd)
   1893         error.output = output
-> 1894         raise error
   1895     return output
   1896 except KeyboardInterrupt:

CalledProcessError: Command '/home/zhang_lab/software/mallet-2.0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input /DATA1/wangrong/temp/ray_spill/corpus.txt --output /DATA1/wangrong/temp/ray_spill/corpus.mallet' returned non-zero exit status 1.

**Expected behavior**
I am a new user of Java, but pycistopic is a very good software for me to use step by step. I want to get the output of the model.Or maybe there's a good way to run it for my dataset please let me know. Thank you
**Screenshots**
If applicable, add screenshots to help explain your problem or show the format of the input data for the command/s.

**Version (please complete the following information):**
 - java 11.0.17
 - mallet-2.0.8
 - python 3.8
 -ps;Our supercomputer has a 64-core 256cpu with 1T of physical memory and more than 10T of storage space

**Additional context**
I checked that the mallet import-file corpus.txt  size is 29G, and the java configuration information is as follows
java -XX:+PrintFlagsFinal -version | grep -iE 'HeapSize'
   size_t ErgoHeapSizeLimit                        = 0                                         {product} {default}
   size_t HeapSizePerGCThread                      = 43620760                                  {product} {default}
   size_t InitialHeapSize                          = 2147483648                                {product} {ergonomic}
   size_t LargePageHeapSizeThreshold               = 134217728                                 {product} {default}
   size_t MaxHeapSize                              = 32178700288                               {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 12297104                               {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 119680568                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 119680568                              {pd product} {ergonomic}
   size_t ShenandoahSoftMaxHeapSize                = 0                                      {manageable} {default}
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)

**Comment by WangRong423** [comment]
I have solved the problem. By changing .bashrc ‘export _JAVA_OPTIONS=-Xmx250g’ and running the py script from the command line, not jupyter. Thank you very much

**Comment by MariaRosariaNuceraPhD** [comment]
>Thank you @WangRong423 
I have the same problem and same versions of java, mallet and python.
Any ways to solve it from jupyter instead of the command line?

**Comment by Sebdumas** [comment]
@MariaRosariaNuceraPhD I had the same issue and solved it in Jupyter adding 
`os.environ['MALLET_MEMORY'] = '200G'`
before running `run_cgs_models_mallet()`

Without specifying Mallet memory in jupyter, Mallet was calling Java with maximum heap size of 1G. It uses now the 200G value has maximum heap size.
